---
- name: Execute bash script on master server
  hosts: slave
  tasks:
    - name: Copy bash script to slave
      copy:
        src: cloud_lamp.sh
        dest: /Wole_exam/cloud_lamp.sh
        mode: 0755

    - name: Run bash script on master server
      shell: sh /Wole_exam/cloud_lamp.sh