Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"

  # Define the Ubuntu 20.04 box for master
  config.vm.define "master" do |master|
    master.vm.box = "bento/ubuntu-20.04"
    master.vm.hostname = "master"
    master.vm.network :private_network, ip: "192.168.56.21"

    master.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 2
    end
  end

  # Define the Ubuntu 20.04 box for slave
  config.vm.define "slave" do |slave|
    slave.vm.box = "bento/ubuntu-20.04"
    slave.vm.hostname = "slave"
    slave.vm.network :private_network, ip: "192.168.56.22"

    slave.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 2
    end
  end
end